# Generated by Django 5.0.7 on 2024-07-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='documents/pdfs/')),
                ('p12', models.FileField(upload_to='documents/p12s/')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
